make:
	javac XKCDPasswordGenerator.java
	chmod +x xkcdpwgen

run:
	javac XKCDPasswordGenerator.java
	java XKCDPasswordGenerator

clean:
	rm XKCDPasswordGenerator.class

# Instructions to Run:
# 1. make
# 2. ./xkcdpwgen <args-flags-you-desire>